sudo: required
services:
  - docker

before_install:
  - docker build -t vijayrajan23/react -f Dockerfile.dev .

script:
  - docker run -e CI=true vijayrajan23/react npm run test


deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Nila"
  env: "Nila-env"
  bucket_name: "elasticbeanstalk-ap-south-1-907225840730"
  bucket_path: "Nila"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
